name: CI
on: [push]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Backend
        run: |
          pip install flask pytest pytest-cov flask-jwt-extended flask-cors sqlalchemy
          pytest --cov=src

      - name: Frontend
        run: |
          cd src/frontend
          npm install
          npx vitest